name: MCFoodRegen
version: ${project.version}
main: io.github.douglasb2310.mcfoodregen.FoodRegen
authors: [DouglasB2310]
description: Disables hunger, natural health regeneration and makes food regenerate players' health.
website: https://github.com/DouglasB2310/MCFoodRegen
